import { useEffect, useState } from 'react';
import axios from 'axios';
import Navbar from './shared/Navbar';
import { API_END_POINT } from '@/utils/constant';
import CompanyAvatar from './CompanyAvatar';

const Stat = ({ label, value }) => <section className="rounded-lg border bg-white p-5 shadow-sm"><p className="text-sm text-gray-500">{label}</p><p className="mt-1 text-3xl font-bold text-[#6A38C2]">{value ?? 0}</p></section>;
const Empty = () => <p className="text-sm text-gray-500">Nothing to show yet.</p>;

export default function Dashboard({ role }) {
  const [data, setData] = useState(null); const [error, setError] = useState('');
  useEffect(() => { axios.get(`${API_END_POINT}/dashboard`, { withCredentials: true }).then(({ data: result }) => setData(result)).catch((err) => setError(err.response?.data?.message || 'Unable to load dashboard.')); }, []);
  const candidate = role === 'candidate'; const stats = data?.statistics || {};
  return <><Navbar /><main className="mx-auto my-8 max-w-7xl px-4 sm:px-6"><h1 className="mb-6 text-2xl font-bold">{candidate ? 'Candidate dashboard' : 'Employer dashboard'}</h1>{error && <p className="text-red-600">{error}</p>}{data && <><div className="grid grid-cols-2 gap-4 lg:grid-cols-5">{candidate ? <><Stat label="Applications" value={stats.totalApplications} /><Stat label="Pending" value={stats.pendingApplications} /><Stat label="Accepted" value={stats.acceptedApplications} /><Stat label="Rejected" value={stats.rejectedApplications} /><Stat label="Saved jobs" value={stats.totalSavedJobs} /></> : <><Stat label="Total jobs" value={stats.totalJobs} /><Stat label="Active jobs" value={stats.activeJobs} /><Stat label="Closed jobs" value={stats.closedJobs} /><Stat label="Total applicants" value={stats.totalApplicants} /></>}</div><div className="mt-8 grid gap-5 lg:grid-cols-2"><section className="rounded-lg border bg-white p-5"><h2 className="mb-3 font-semibold">{candidate ? 'Recent applications' : 'Recent jobs'}</h2>{(candidate ? data.recentApplications : data.recentJobs)?.length ? <div className="space-y-3">{(candidate ? data.recentApplications : data.recentJobs).map((item) => { const job = candidate ? item.job : item; return <div key={item._id} className="flex flex-wrap items-center justify-between gap-2 border-b pb-2 text-sm"><div className="flex items-center gap-2"><CompanyAvatar job={job} className="h-8 w-8" /><span className="font-medium">{job?.title}</span></div><span>{job?.company?.name}</span><span className="capitalize text-gray-500">{candidate ? item.status : job?.status}</span></div>; })}</div> : <Empty />}</section><section className="rounded-lg border bg-white p-5"><h2 className="mb-3 font-semibold">{candidate ? 'Recent saved jobs' : 'Recent applications'}</h2>{(candidate ? data.recentSavedJobs : data.recentApplications)?.length ? <div className="space-y-3">{(candidate ? data.recentSavedJobs : data.recentApplications).map((item) => { const job = candidate ? item.job : item.job; return <div key={item._id} className="flex flex-wrap items-center justify-between gap-2 border-b pb-2 text-sm">{candidate ? <div className="flex items-center gap-2"><CompanyAvatar job={job} className="h-8 w-8" /><span className="font-medium">{job?.title}</span></div> : <span className="font-medium">{job?.title}</span>}<span>{candidate ? job?.company?.name : item.applicant?.fullname}</span><span className="capitalize text-gray-500">{candidate ? job?.status : item.status}</span></div>; })}</div> : <Empty />}</section></div></>}</main></>;
}
