import { createBrowserRouter, Navigate, RouterProvider } from 'react-router-dom';
import Login from './components/auth/Login'; import Signup from './components/auth/Signup'; import Home from './components/Home'; import Jobs from './components/Jobs'; import Browse from './components/Browse'; import Profile from './components/Profile'; import JobDescription from './components/JobDescription';
import Companies from './components/admin/Companies'; import CompanyCreate from './components/admin/CompanyCreate'; import CompanySetup from './components/admin/CompanySetup'; import AdminJobs from './components/admin/AdminJobs'; import PostJob from './components/admin/PostJob'; import EditJob from './components/admin/EditJob'; import Applicants from './components/admin/Applicants'; import ProtectedRoute from './components/admin/ProtectedRoute'; import SavedJobs from './components/SavedJobs'; import Applications from './components/Applications'; import AdminDashboard from './components/admin/AdminDashboard'; import Dashboard from './components/Dashboard';
const employer = (element) => <ProtectedRoute roles={['employer']}>{element}</ProtectedRoute>; const admin = (element) => <ProtectedRoute roles={['admin']}>{element}</ProtectedRoute>;
const appRouter = createBrowserRouter([
  { path: '/', element: <Home /> }, { path: '/login', element: <Login /> }, { path: '/signup', element: <Signup /> }, { path: '/register', element: <Signup /> }, { path: '/jobs', element: <Jobs /> }, { path: '/jobs/:id', element: <JobDescription /> }, { path: '/description/:id', element: <JobDescription /> }, { path: '/browse', element: <Browse /> },
  { path: '/profile', element: <ProtectedRoute roles={['candidate']}><Profile /></ProtectedRoute> }, { path: '/candidate/dashboard', element: <ProtectedRoute roles={['candidate']}><Dashboard role="candidate" /></ProtectedRoute> }, { path: '/applications', element: <ProtectedRoute roles={['candidate']}><Applications /></ProtectedRoute> }, { path: '/saved-jobs', element: <ProtectedRoute roles={['candidate']}><SavedJobs /></ProtectedRoute> },
  { path: '/employer/dashboard', element: employer(<Dashboard role="employer" />) }, { path: '/employer/companies', element: employer(<Companies />) }, { path: '/employer/companies/create', element: employer(<CompanyCreate />) }, { path: '/employer/companies/:id', element: employer(<CompanySetup />) }, { path: '/employer/jobs', element: employer(<AdminJobs />) }, { path: '/employer/jobs/create', element: employer(<PostJob />) }, { path: '/employer/jobs/:id/edit', element: employer(<EditJob />) }, { path: '/employer/jobs/:id/applicants', element: employer(<Applicants />) }, { path: '/admin/dashboard', element: admin(<AdminDashboard />) }
]);
export default function App() { return <RouterProvider router={appRouter} />; }
